name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup cache for Nix
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix flake
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      - name: Setup environment (nix develop)
        uses: nicknovitski/nix-develop@v1

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Lint
        run: |
          just lint

      - name: Spell check
        run: |
          just spell-check

      # Need to make sure this stays in line with `just ci`.
      - name: Run tests (generate JUnit)
        run: |
          cargo nextest --profile ci run --all-targets --all-features --verbose

      - name: Publish Test Results
        if: (!cancelled())
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: target/nextest/ci/*.xml
